### ISSUE TITLE
Promises Working Group, Call For Contributors

### ISSUE THREAD

**Issue by benjamingr** [nodejs/promises#1]
The recent issues raised in https://github.com/nodejs/node/pull/5020 https://github.com/nodejs/post-mortem/issues/16 https://github.com/groundwater/nodejs-symposiums/pull/5 and https://github.com/groundwater/nodejs-symposiums/pull/6 have shown that we still have a _lot_ of ground to cover in terms of how promises interact with NodeJS.

Currently discussion is a little disorganized, a lot of discussion is happening and a lot of discussion should still happen.

There are a lot of open issues that would be in scope like:
- How can debugging be made easier in Node for promise users.
- Post mortem debugging with promises.
- Promise cancellation and how APIs would interact with it when it lands.
- How async/await support would look like.
- How promise APIs would look like in core.
- Documentation of V8's implementation, what hooks it provides and how to work with it.
- How to make sure promises don't get in the way of callback users with core support.
- How/if to get AsyncWrap to work with promises.
- General group to deal with promise related bugs.

These issues all need to be discussed at depth. We need to document them, create a knowledge base and seek good solutions. The WG would operate under the TSC.

I'd love to see people step up and participate. In particular I'd love to see the following people in the WG. I'm looking for more community involvement so please feel free to suggest yourself for the WG: 
- @chrisdickinson 
- @domenic
- @petkaantonov
- @spion
- @vkurchatkin
- @thefourtheye
- @iamstef
- @kriskowal
- @bnoordhuis
- @trevnorris

**Comment by bnoordhuis** [comment]
I'm happy to provide input every now and again but I don't really have time to sit on another WG.  Feel free to pull me into (online) technical discussions.

**Comment by vkurchatkin** [comment]
I'm in!

**Comment by trevnorris** [comment]
sure

**Comment by chrisdickinson** [comment]
I would be happy to facilitate this group.

I would recommend that we define the lifecycle of this WG: the first stage should be focused on the nodejs/node#5020 PR, and making sure it's in a shape that we're comfortable landing it flagged. This means that we'll be doing some triage — seeking consensus on which issues to defer resolving until the PR is landed, and which need addressed immediately.

The second stage of this WG's lifecycle should be making sure that all issues that come up during flagging (and all issues deferred to flagging) are addressed. The second stage should be focused on developing a "go / no go" check that is acceptable to all involved, so that we know whether or not the feature is ready to be unflagged.

The third stage of this WG will be advisory — once the the Promises API is unflagged, this WG should serve in an advisory capacity for Promise-related issues and features for Node core.

Does this sound acceptable?

**Comment by petkaantonov** [comment]
Chris, sounds good to me

**Comment by benjamingr** [comment]
@trevnorris @vkurchatkin that's great news, thanks!

---

That sounds good to me @chrisdickinson :+1: 

I just want to make sure that we do not neglect issues related to async/await in Node, cancellation when it comes in v8, how to deal with asyncwrap and other issues.

What do you think about moving the issues regarding the recovery object API to this repo? (I don't have a strong opinion about it).

@misterdjules @groundwater please do come by and participate.

**Comment by kriskowal** [comment]
I am available to answer questions, share opinions, and review code. I may be able to attend a face to face very occasionally. I can commit to turn-around times on the order of a week, but not on the order of a day. I do not wish to impede progress, so I would ask this WG not to block on my contributions.

It may be good to include @Raynos to keep this WG honest about ensuring that promises are an opt-in affordance.

**Comment by benjamingr** [comment]
@kriskowal working groups do not block on the contributions of a single member. I would love to have you around as the author of one of the fathers of JS promises and a very insightful individual on the topic. 

Being a part of the WG means you will get pinged occasionally on issues related to promises and invited to participate in conversations. It does not require you to make any long term time commitment but you are expected to be available every now and then. 

@Raynos has not shown an interest in the past and I'm afraid he would not be interested in looking for ways to improve promises support. I'll be sure to ping him on issues though. (Of course, if he comes by and expresses direct interest to contribute time and effort it changes everything).

**Comment by phpnode** [comment]
Agree about including @raynos if he has the desire/availability, it is better to consider the kinds of concerns he has now rather than agreeing something here, only to have it cause problems later.

**Comment by kriskowal** [comment]
@benjamingr As such, consider me a participant. Hope to help.

**Comment by chrisdickinson** [comment]
As a heads up for participants, I do not expect that this WG will hold regular face-to-face meetings. I will instead focus on setting up an IRC channel for ad-hoc communication that doesn't need to be recorded in-issue.

**Comment by benjamingr** [comment]
Yes +1 for no regular face-to-face meetings at least until we have a very convinging reason to hold them. IRC (or slack) sounds entirely reasonable.

**Comment by MadaraUchiha** [comment]
Count me in (should you take me), I'm probably not half as knowledgeable as most people in this group, but I think I might know enough to not make a **complete** fool of myself.

**Comment by omsmith** [comment]
@benjamingr Would like to throw my hat in the ring here - will follow the discussion either way.

**Comment by thefourtheye** [comment]
I would love to be a part of this. Thanks @benjamingr for the mention :-)

**Comment by balupton** [comment]
> I would recommend that we define the lifecycle of this WG: the first stage should be focused on the nodejs/node#5020 PR, and making sure it's in a shape that we're comfortable landing it flagged.

I'm not sure what this actually means. The discussions within 5020 has become a conglomeration of various proposals and concerns, all of which seems to be in a state of flux. So either there exists some hidden consensus of what is going to be merged, or there is no consensus yet. Either way it needs to actually be defined what this first stage is, and what the proposed changes or various proposals with their differing support, actually and currently, are - as otherwise it is impossible to follow for someone without the ability to keep up to date daily.

For instance, just with the concern "How promise APIs would look like in core", even inside the PR there seems to be no consensus. I've created https://github.com/nodejs/promises/issues/16 to create some refuge in trying to keep up to date with that topic alone.

The ideal for dealing with this seems to be breaking out each different issue/concern that was raised into its own thread on this repo, then perhaps with sub/linked threads for each of the proposals for each concern, so one can adequately mark the support for each proposal and concern, along with each stage it is for. As otherwise, the knowledge of what is actually going on, could remain inaccessible to those not keeping up to date every day.

---

> Participation We are currently looking for more participants in the working group - see https://github.com/nodejs/promises/issues/1

For the WG, is it necessary to be part of the WG before adding to the discussion? Who is the WG open to? Are long-term or prominent module authors also possible candidates, or is it limited to node core contributors?

**Comment by tjwebb** [comment]
Hey guys, I'm interested in helping out. Any guidance on how much time per week I should expect to devote to the group?

**Comment by chrisdickinson** [comment]
@balupton: While the conversation has gone on for a bit, for the most part the strategy and implementation proposed have not changed. We may nix the commit introducing the recovery object, but otherwise what's proposed has been stable for a week or two. The parts in flux are the conversations around how to address the concerns of users that wish to avoid exceptional error handling in `async/await` programs, and how to address the concerns of post-mortem users. The proposal right now is in line with what's described in [this post](https://medium.com/@isntitvacant/adding-promise-support-to-core-a4ea895ccbda).

**Comment by chrisdickinson** [comment]
@balupton: I've updated #16 to reflect the current status of the proposal, and will keep that updated as time goes on.

**Comment by chrisdickinson** [comment]
Re: Joining the discussion — no need to be an official part of the WG. Once the WG reaches [stage 2](https://github.com/nodejs/promises/#stage-2-continued-support), members may begin to receive emails about issues @-mentioning the Promises WG, but until that point the WG mostly exists to curate, advocate, and facilitate the promises discussion in this repo (and in the pull request on GitHub.)

**Comment by jorgebay** [comment]
I would be glad to join as community member of the WG!

**Comment by phpnode** [comment]
I'm happy to participate. It would be good to get a slack, gitter or IRC room set up.

**Comment by balupton** [comment]
> but until that point the WG mostly exists to curate, advocate, and facilitate the promises discussion in this repo (and in the pull request on GitHub.)

I'm happy to help. My usage of node necessitates my understanding of this. So happy to understand, and help with those tasks, while adding my perspectives as a module author with experience in these areas.

**Comment by vdeturckheim** [comment]
I would love to join this WG !

**Comment by jasnell** [comment]
I'm not putting my name in for the WG but I do intend on participating in the discussion as time allows.

**Comment by rkotangoor** [comment]
Looking forward to participate, I recently started using promises and want to learn more in depth.

**Comment by vramana** [comment]
I am also looking forward to participate here.

**Comment by Fishrock123** [comment]
I'll have input from time to time but I simply don't have the time/energy to fully participate.

**Comment by DonutEspresso** [comment]
I'm happy to be a peripheral observer - will provide feedback and perspective as needed.

**Comment by misterdjules** [comment]
@benjamingr @chrisdickinson 

Thank you for the mention. What participation is required from a member of this WG? For instance, will there be periodic meetings?

I'm currently focused on trying to help the project better understand the impact of https://github.com/nodejs/node#5020 on post-mortem debugging users, and find a technical solution if some problems are identified.

I won't have time to be involved in anything that does not involve post-mortem debugging, so I'm not sure if I need to be formally part of this working group. I will however be happy to provide feedback and help whenever requested.

**Comment by williamkapke** [comment]
Great to see all of this discussion. I definitely want to contribute! I have a ton of experience working with  Promises in large scale production environments.

Curious, how does this relate to: https://github.com/nodejs/NG/issues/25 ? There seem to be so many places to discuss this topic.

**Comment by petkaantonov** [comment]
Those threads were created before this WG existed, all promise discussion should happen here now on appropriate issue

**Comment by stephenhuh** [comment]
@benjamingr I'd love to help contribute and think I could help quite a bit.

**Comment by benjamingr** [comment]
@stephenhuh hey, the current work is at https://github.com/nodejs/node/pull/12442 - you're welcome to take a look and review the code. Also, https://github.com/nodejs/CTC/issues/12

**Comment by refack** [comment]
> @stephenhuh hey, the current work is at nodejs/node#12442 - you're welcome to take a look and review the code. Also, nodejs/CTC#12

So are you saying that this WG has concluded it's work?
(cause I'd love to help. I re-wrote and still maintain https://github.com/aheckmann/mpromise, one of the earlier A+ compliant libraries, an unfortunately because of `mongoose` still one of the most used ones https://npm-stat.com/charts.html?package=mpromise&from=2015-01-01&to=2017-04-20)

**Comment by benjamingr** [comment]
@refack it is stalled, I don't think it concluded its work until we have promises in core.

It's mostly stalled on v8 work though, you're welcome to participate!

**Comment by refack** [comment]
> It's mostly stalled on v8 work though, you're welcome to participate!

Point me in the right direction, ain't afraid of V8 code ;)
